version: '3'

networks:
  openai:

services:
  yui:
    image: gpt-discord:dev
    volumes:
      - ./config:/config
      - /etc/ssl/certs:/etc/ssl/certs
    restart: unless-stopped
    networks:
      - openai
